### ISSUE TITLE
Looks like user site crashes when opened with active (in browser cache/storage/whatever) admin session (?)

### ISSUE THREAD

**Issue by mshekera** [winnlab/AgushaHuge#8]
Occurs after `coffee init` and loading main page (`http://somehost:8080`). Maybe requires fresh repository deployment to reproduce.

Once, few days ago, resolved the problem, but have no idea actually how. Maybe something related to caching?

Error log/stack:

```
undefined:445
if (user && user.getImage('min'))
                 ^
TypeError: Object { _id: 53b54577f5adc6a9932b1aec,
  username: 'admin',
  email: 'admin@admin.com',
  password: '79e262a81dd19d40ae008f74eb59edce',
  __v: 0,
  created_at: 1417114758113,
  status: 1,
  role: 'admin' } has no method 'getImage'
  at eval (<anonymous>:445:18)
  at eval (<anonymous>:457:39)
  at Array.res [as user/main/index] (/home/olmdar/Projects/AgushaHuge/node_modules/jade/lib/jade.js:175:38)
  at Object.exports.render.render [as render] (/home/olmdar/Projects/AgushaHuge/lib/view.coffee:33:9)
  at /home/olmdar/Projects/AgushaHuge/controllers/user/main.coffee:81:8
  at /home/olmdar/Projects/AgushaHuge/controllers/user/main.coffee:45:3
  at /home/olmdar/Projects/AgushaHuge/node_modules/async/lib/async.js:592:17
  at done (/home/olmdar/Projects/AgushaHuge/node_modules/async/lib/async.js:135:19)
  at /home/olmdar/Projects/AgushaHuge/node_modules/async/lib/async.js:32:16
  at /home/olmdar/Projects/AgushaHuge/node_modules/async/lib/async.js:589:21
  at Promise.<anonymous> (/home/olmdar/Projects/AgushaHuge/controllers/user/main.coffee:31:3)
  at Promise.<anonymous> (/home/olmdar/Projects/AgushaHuge/node_modules/mongoose/node_modules/mpromise/lib/promise.js:177:8)
  at Promise.EventEmitter.emit (events.js:95:17)
  at Promise.emit (/home/olmdar/Projects/AgushaHuge/node_modules/mongoose/node_modules/mpromise/lib/promise.js:84:38)
  at Promise.fulfill (/home/olmdar/Projects/AgushaHuge/node_modules/mongoose/node_modules/mpromise/lib/promise.js:97:20)
  at Object.cb (/home/olmdar/Projects/AgushaHuge/node_modules/mongoose/lib/query.js:1010:22)
  at Object._onImmediate (/home/olmdar/Projects/AgushaHuge/node_modules/mongoose/node_modules/mquery/lib/utils.js:137:16)
  at processImmediate [as _immediateCallback] (timers.js:330:15)
```

**Comment by mshekera** [comment]
Do not know whos bug this is.
I suppose problem occurs when logged in as admin (I mean from User model, not from Client).
Maybe could be fixed by changing

``` javascript
if (user && user.getImage('min'))
```

to:

``` javascript
if (user && user.getImage && user.getImage('min'))
```

?

**Comment by Rastopyr** [comment]
вообще этот шаблон можно удалить, профиль грузиться только с сервера и извне недоступно.
но мне не нравится такой подход, нужно сделать какую нибудь мультипл сериализацию пользователей. или как нибудь по другому разделить.
